package types

type SessionTicket struct {
	Id        int // this identifies the session
	Nonce     int // randomly generated by client
	Signature int // murmur hash truncated to int of the nonce with the secure session token
}
